[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_dapp_project = "GVVbqMSb93rYpUoCWAZajhKa5ZYYqZzNvQ3Zn2ULJP3W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/workspaces/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
